#!/bin/bash
yum update -y
yum install nginx -y
systemctl start nginx
systemctl enable nginx
# Opcional para crear la estructura de ficheros que almacenara el index.html
echo "<h1>Hello World</h1>" > /usr/share/nginx/html/index.html
