#!/bin/bash
yum update -y
yum install nginx -y
systemctl start nginx
systemctl enable nginx
# Opcional para crear el fichero que almacenara el index.html 
# sudo echo "<h1>Hello World</h1>" | sudo tee /usr/share/nginx/html/index.html
